### ISSUE TITLE
CompileModule?

### ISSUE THREAD

**Issue by phated** [ry/v8worker2#1]
First of all, I wanted to say thank you for this project (and v1)!  I am super excited about it and have been following for a long time.

Anyway, what would think about using `ScriptCompiler::CompileModule` instead of `Script::Compile`?  I did some experiments at https://github.com/phated/v8worker2/blob/modules/binding.cc#L252-L271 (Please note that I don't know C at all, so it's probably terrible code.) because I didn't understand why `import`/`export` were invalid syntax.

Maybe it makes sense as a separate API?  I also wonder if `CompileModule` works any differently from `Compile` for script-style JS code.

**Comment by ry** [comment]
Interesting - I didn't know about that!

Yes, I think we should have this functionality. Is your code working? I haven't given it a through look but it seems `moduleMap` should be a  `std::map<string, Persistent<Module>>` ?

**Comment by phated** [comment]
I couldn't get the module loading working due to my extreme C naivety, but I could give your suggestion a try.

**Comment by ry** [comment]
Yeah, give it a shot - that's the one way to improve C naivety. Feel free to email me questions.

**Comment by phated** [comment]
I made the suggested changes (at https://github.com/phated/v8worker2/blob/modules/binding.cc#L158-L230) and it's picking up the module now but something is still wrong - I'm pretty sure I'm missing some details about V8 internals.

**Comment by ry** [comment]
Great! I have some comments, but it seems I'm not able to comment until you start PR. Please open a PR and let's move the discussion there.

Also there should be tests. How are you testing now?

**Comment by phated** [comment]
Will do!  I'll put some cleanup touches (tests, rebase) and submit a PR this afternoon.
