### ISSUE TITLE
[Doc] build.py only support Python2

### ISSUE THREAD

**Issue by ipfans** [ry/v8worker2#5]
build.py used keywords like `print` that only works in Python2. I think it should be figure out.

And as docs I think more clarify desc will be:

```
cd `go env GOPATH`/src/github.com/ry
git clone https://github.com/ry/v8worker2.git
cd v8worker2
./build.py
...
```

First installation with `go get` will be error not found `v8.pc`, which generated after exec `build.py`. This will be confused for beginners.

**Comment by ry** [comment]
Yeah, shouldn't be too hard to do - PRs welcome.

> First installation with go get will be error not found v8.pc, which generated after exec build.py. This will be confused for beginners.

Yes... there's nothing that can be done about this, I'm afraid. (I'd be happy to be corrected tho.)
